### ISSUE TITLE
Updated vcd_vapp_vm_nic.py, not taking state 'update' and adapter_type is a mandatory field

### ISSUE THREAD

**Issue by monadhiman** [vmware/ansible-module-vcloud-director#122] opened 2020-06-11 12:48 UTC
Hi Team,

As I was testing the updated modules, I found vcd_vapp_vm_nic is not working as expected with update state and also it is giving error if I do not give adapter_type.

Please find below logs for reference:

- TypeError: Value of unknown type: <class 'AttributeError'>, 'VM' object has no attribute 'update_nic'

 - cvc-elt.3.1: Attribute 'http://www.w3.org/2001/XMLSchema-instance,nil' must not appear on element 'NetworkAdapterType', because the {nillable} property of 'NetworkAdapterType' is false. (request id: 173b3793-28df-463d-93c3-b5363730def5)

Thank You.

**Comment by mukultaneja** [comment] 2020-06-22 20:07
Could you please share the playbook and complete error traceback?

**Comment by monadhiman** [comment] 2020-06-24 08:57
> 
> 
> Could you please share the playbook and complete error traceback?

This is the part of playbook, I am getting error with:

 - name: update EIN NIC
    vcd_vapp_vm_nic:
        vm_name: "{{VmName}}"
        vapp: "{{VappName}}"
        vdc: "{{VdcName}}"
        nic_id: 0
        network: "{{Network[0].name}}"
        ip_allocation_mode: "MANUAL"
        ip_address: "{{Network[0].ipaddress}}"
        state: "update"
        
Below is the error code with update state:

fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:
.......

Traceback (most recent call last):
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_0r4zf8rg/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 280, in main
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_0r4zf8rg/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 157, in manage_states
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_0r4zf8rg/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 226, in update_nic
AttributeError: 'VM' object has no attribute 'update_nic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1592988474.47-116190528470640/AnsiballZ_vcd_vapp_vm_nic.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1592988474.47-116190528470640/AnsiballZ_vcd_vapp_vm_nic.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1592988474.47-116190528470640/AnsiballZ_vcd_vapp_vm_nic.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.vcd_vapp_vm_nic', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_0r4zf8rg/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 294, in <module>
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_0r4zf8rg/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 288, in main
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_0r4zf8rg/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py", line 2093, in fail_json
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_0r4zf8rg/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py", line 2065, in _return_formatted
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_0r4zf8rg/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py", line 418, in remove_values
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_0r4zf8rg/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py", line 401, in _remove_values_conditions
TypeError: Value of unknown type: <class 'AttributeError'>, 'VM' object has no attribute 'update_nic'


++++++++++
**When I changed the state to present, I got below error:**


Traceback (most recent call last):
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_htwr2iu8/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 280, in main
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_htwr2iu8/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 154, in manage_states
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_htwr2iu8/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 206, in add_nic
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/vm.py", line 450, in add_nic
    EntityType.NETWORK_CONNECTION_SECTION.value, net_conn_section)
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1198, in put_linked_resource
    media_type)
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1182, in put_resource
    params=params)
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 982, in _do_request
    _objectify_response(response, objectify_results))
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 987, in _response_code_to_exception
    raise BadRequestException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.BadRequestException: Status code: 400/BAD_REQUEST, [ 0de6fffe-2f30-4b0e-a800-7305de9d9603 ] HTTP 400 Bad Request
 - cvc-elt.3.1: Attribute 'http://www.w3.org/2001/XMLSchema-instance,nil' must not appear on element 'NetworkAdapterType', because the {nillable} property of 'NetworkAdapterType' is false. (request id: 0de6fffe-2f30-4b0e-a800-7305de9d9603)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1592988541.03-237080633342272/AnsiballZ_vcd_vapp_vm_nic.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1592988541.03-237080633342272/AnsiballZ_vcd_vapp_vm_nic.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1592988541.03-237080633342272/AnsiballZ_vcd_vapp_vm_nic.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.vcd_vapp_vm_nic', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_htwr2iu8/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 294, in <module>
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_htwr2iu8/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 288, in main
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_htwr2iu8/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py", line 2093, in fail_json
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_htwr2iu8/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py", line 2065, in _return_formatted
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_htwr2iu8/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py", line 418, in remove_values
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_htwr2iu8/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py", line 401, in _remove_values_conditions
TypeError: Value of unknown type: <class 'pyvcloud.vcd.exceptions.BadRequestException'>, Status code: 400/BAD_REQUEST, [ 0de6fffe-2f30-4b0e-a800-7305de9d9603 ] HTTP 400 Bad Request
 - cvc-elt.3.1: Attribute 'http://www.w3.org/2001/XMLSchema-instance,nil' must not appear on element 'NetworkAdapterType', because the {nillable} property of 'NetworkAdapterType' is false. (request id: 0de6fffe-2f30-4b0e-a800-7305de9d9603)



Thank You.

**Comment by mukultaneja** [comment] 2020-06-24 19:34
@monadhiman thanks for sharing the logs. 
1. `TypeError: Value of unknown type: <class 'AttributeError'>, 'VM' object has no attribute 'update_nic'` 
Please confirm if you are using the latest versions of pyvcloud and these modules as we dont use `nic_id` anymore to update nic cards. Please check that Modules wiki [here](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM-Nic) and pyvcloud method [here](https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcd/vm.py#L1239)

2. Attribute 'http://www.w3.org/2001/XMLSchema-instance,nil' must not appear on element 'NetworkAdapterType', because the {nillable} property of 'NetworkAdapterType' is false. (request id: 0de6fffe-2f30-4b0e-a800-7305de9d9603)
Could you please try with a `adapter_type` like [here](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM-Nic)

**Comment by monadhiman** [comment] 2020-06-26 09:42
Hello @mukultaneja,

=> I am using pyvcloud-20.1.0. 

I saw the code was updated 2 days ago but that should not be the issue as this issue is with vcd_vapp_vm_nic which was updated 2 months back so I am using the latest version of this module.

=> I tried with adapter_type with state present and it works as expected with nic_ids.  It does not work with update state.

Thank you.

**Comment by mukultaneja** [comment] 2020-06-27 18:04
I updated the module last month exact to be 8th May. And as I said I am not using nic_ids now in the module. Please take a look at [once](https://github.com/vmware/ansible-module-vcloud-director/blob/master/modules/vcd_vapp_vm_nic.py)

**Comment by monadhiman** [comment] 2020-07-02 11:25
hello @mukultaneja ,

I downloaded the code again ( with check mode changes ) and tested to be sure of this issue.
Even if I dont use nic_ids parameter at all, I am getting the same error while updating the NIC.

TypeError: Value of unknown type: <class 'AttributeError'>, 'VM' object has no attribute 'update_nic'
 
Thank you.

**Comment by mukultaneja** [comment] 2020-07-07 19:31
@monadhiman, I am afraid that I am not able to reproduce the issue. For me, it is working perfectly. Below is the playbook which I am using and respective output to that. Please let me know If I am missing something which you are doing extra.

```
- name: update vm nic
  vcd_vapp_vm_nic:
    user: acmeadmin
    password: ******
    org: Acme
    vapp: acme_vapp
    vm_name: centos
    vdc: ACME_PAYG
    network: acme_vapp_network
    is_primary: True
    state: update
  register: output


- name: update vm nic output
  debug:
    msg: '{{ output }}'

```

```

PLAY [Ansible Modules for vCloudDirector] *************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************
ok: [localhost]

TASK [vcd_vapp_vm_nic : update vm nic] ****************************************************************************************************************
changed: [localhost]

TASK [vcd_vapp_vm_nic : update vm nic output] *********************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": true,
        "failed": false,
        "msg": "A nic attached with VM centos has been updated"
    }
}

PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

**Comment by monadhiman** [comment] 2020-07-09 10:27
@mukultaneja Hi,

This is strange, even when I tried to execute above mentioned code , I am getting the same issue. 
TypeError: Value of unknown type: <class 'AttributeError'>, 'VM' object has no attribute 'update_nic'

Moreover the issue indicates much on module side but same module is working fine for you. :|

Even I have updated pyvcloud to 22.0 not sure what is the issue in my case :(
Still checking further..

Thank You.

**Comment by mukultaneja** [comment] 2020-08-06 20:12
@monadhiman, are you able to resolve the issue yet?

**Comment by monadhiman** [comment] 2020-10-08 08:09
> 
> 
> @monadhiman, are you able to resolve the issue yet?

Hi @mukultaneja,  No, this new module file did not work for me,  I made some changes in the old module file and using the same to have an error free action and that is working fine for me.

Thank You.

**Comment by mukultaneja** [comment] 2020-10-19 20:08
Sure, please close it and feel free to reopen it if you find any issues again.

**Comment by sgutermann** [comment] 2020-10-29 23:03
@mukultaneja ...having same problem. If I do your sample all works fine. As there is nothing to update anyway. As soon as you add a second network and then want to update / add a second nic to the VM there seems to be no longer a way.

Old Module and old way still work fine. 

What I am trying currently is:

      - name: VMWARE_CLOUDDIRECTOR_CREATE_VM | Create vapp vm secondary nic
        vcd_vapp_vm_nic:
          vm_name: "{{ inventory_hostname }}"
          vapp: "{{ inventory_hostname }}"
          vdc: "{{ vdc }}"
          network: "{{ bechtlecloud.secondnetwork }}"
          ip_allocation_mode: "MANUAL"
          ip_address: "{{ bechtlecloud.secondip }}"
          is_primary: False
          is_connected: True
          adapter_type: "VMXNET3"
          state: "present"

(if present or update makes no difference)

Error:

'VM' object has no attribute 'add_nic'\n"

If this is not the way to add a second Nic to my VM then please let me know how this is done now.

**Comment by sgutermann** [comment] 2020-10-29 23:07
'VM' object has no attribute 'update_nic'\n

**Comment by sgutermann** [comment] 2020-10-29 23:41
OMG - forget my two postings. This is really strange. Everytime I update, I simply copy the code into my plugins folder. This now produces strange errors. 

After completely deleting everything under plugins and copy freshly the disappeared.

**Comment by mukultaneja** [comment] 2020-11-13 19:29
@sgutermann are you able to resolve your issue?

**Comment by sgutermann** [comment] 2020-11-20 10:46
Yes, after completely deleting the old plugin folders the problem was gone. Sorry.

**Closed** 2020-11-20 12:58 UTC
