### ISSUE TITLE
Poweroff operation does not fully poweroff the VM

### ISSUE THREAD

**Issue by monadhiman** [vmware/ansible-module-vcloud-director#92] opened 2019-12-31 11:23 UTC
Hi Team,

I am using below module for doing power off a VM:

name: power off vapp vm
   vcd_vapp_vm:
	target_vm_name: "test_vapp"
	target_vapp: "web2"
	target_vdc: "test_vdc"
	operation: "poweroff"

But when I check Vm shows partially powered off state. which does not allow to delete VM in case I want to.

Could anyone please guide on this.
Thank You.

**Comment by Maunty** [comment] 2020-01-13 12:17
@monadhiman  hi. Power off actually do what it must. The problem is that to remove vm u must to actually undeploy it. Power off from web interface != power of from api, it undeploys vm. 
Btw, seems that undeploy action contains bug. Try to use code from pull request #94 because is still not merged. GL!

**Comment by mukultaneja** [comment] 2020-02-06 19:26
Hi @Maunty, @monadhiman sorry for the delay! I got a little bit confused with undeploy_vm and powered_off VM Operations. Unfortunately, API calls are not that much clear but now I figured out a clear way to power_off a VM. Please take a look and let me know if you still face any issues.

@Maunty, thanks for raising and submitting a pull request. Again, please try out my latest patch!

**Comment by Maunty** [comment] 2020-02-09 20:31
@mukultaneja 
Power off with previous version, module update and then delete action will give an error :)
In fact i liked more then power off did power off and undeploy did undeploy not only undeploy in all cases. But your way of solving issue is less confusing from web ui part of vcloud. Power off action from web ui undeploys vm like your module does.

**Comment by Maunty** [comment] 2020-02-10 09:02
@mukultaneja 
I tested latest patch on 2 different vclouds. It works good.

**Comment by mukultaneja** [comment] 2020-02-11 18:32
cool @Maunty! Thanks for testing it out :)

**Closed** 2020-03-03 18:28 UTC
