### ISSUE TITLE
vcd_vapp_vm does not use 'storage_profile' and 'deploy' parameters during vm creation

### ISSUE THREAD

**Issue by carmineesposito73** [vmware/ansible-module-vcloud-director#23] opened 2018-11-20 17:47 UTC
vcd_vapp_vm does not use 'storage_profile' parameter, it always uses the vdc default storage profile.
vcd_vapp_vm does not use 'deploy' parameter, it always deploys the vm

**Comment by sgutermann** [comment] 2018-11-27 08:44
Either this is resolved and can be closed or my vcloud director is behaving differently.

There are three storrage profiles defined at my site, labelled "Tier1" "Tier2" "Tier3". 

During the creation I can tell it which to use and it works just fine.

**Comment by carmineesposito73** [comment] 2018-11-27 09:15
I use vcloud 8.20 with 27.0 api, I've realized that with
```
            if storage_profile!='':
                spec['storage_profile'] = self.get_storage_profile(storage_profile)
            spec = {k: v for k, v in spec.items() if v}
```
only the default profile is selected, while with
```
            spec = {k: v for k, v in spec.items() if v}
            if storage_profile!='':
                spec['storage_profile'] = self.get_storage_profile(storage_profile)
```
the profile is selected.
Since the line ` spec = {k: v for k, v in spec.items() if v}` is used to eliminate empty values (if I understand well), and the `if storage_profile!='':` checks that the profile is not empty. the order can be changed.
I'm not an expert, it seems to me that ` spec = {k: v for k, v in spec.items() if v}` do not work fine with object.

**Comment by carmineesposito73** [comment] 2018-11-27 14:07
I tried again, I confirm the issue.
I don't think it's important but my storage profile names contain white spaces (e.g. "SATA Storage Profile", "FC Storage Profile")

**Comment by mukultaneja** [comment] 2018-11-27 17:48
@carmineesposito73, can you please try once with updated Pyvcloud version?

**Comment by carmineesposito73** [comment] 2018-11-27 19:12
@mukultaneja I'm using 20.0.1. Is it not the last released?
Anyway I can try tomorrow (my time zone is CET)

**Comment by sgutermann** [comment] 2018-11-29 13:47
I use vcloud 8.20 with 30.0 api. mine works and I do not have any white spaces in my names.

pyvcloud - Version: 20.0.1

**Comment by mukultaneja** [comment] 2018-11-29 18:42
@carmineesposito73 yeah you are correct for PyVcloud API versions but I am not able to reproduce your issue at my end. I have tried profile name with spaces and it is taking correct profile name for me.  There is no as such restriction on Storage Profile name as well [`blog`](https://blogs.vmware.com/vsphere/2013/02/using-storage-profiles-with-vcloud-director-2.html)

@sgutermann better to try with version 27.0/28.0 if you are using vCD 8.20 and 29.0/30.0 are for vCD 9.1 as far I have seen.

**Comment by carmineesposito73** [comment] 2018-11-29 19:12
@mukultaneja if you change line order with `spec = {...} ` before the line that add storage profile, does it work?

The issue is double: can you create an undeployed vm?

**Comment by mukultaneja** [comment] 2018-11-29 19:41
@carmineesposito73, both are same. The order won't make difference here. Ultimately the spec loop will neglect keys if it does not have None/false value.
For another issue, I have made the appropriate change. I would request if you create a separate issue for it so that changes can be tracked.

**Comment by carmineesposito73** [comment] 2018-11-29 21:38
I'll open a second issue and I'll try to add some logs to "my" issue on storage profiles

**Comment by carmineesposito73** [comment] 2018-11-30 15:31
@mukultaneja is there a string inside object spec['storage_profile'] I can print for debuggin purposes?

**Comment by mukultaneja** [comment] 2018-12-01 19:13
@carmineesposito73, you can modify the module code and fill response['msg'] variable with spec['storage_profile']. Apart from this, you can use vCD API interface to verify as well.
So far, allow me to close this issue as I am not able to reproduce the bug. Feel free to open it again if you find more details.

**Closed by mukultaneja** 2018-12-01 19:13 UTC

**Comment by carmineesposito73** [comment] 2018-12-20 14:02
any comment on that?
thanks

**Comment by mukultaneja** [comment] 2019-01-01 17:59
@carmineesposito73, I have added a new commit and hope it would resolve your issue.

**Comment by carmineesposito73** [comment] 2019-01-08 10:48
thanks @mukultaneja , this is the modification I suggested. It works
